### ISSUE TITLE
Error in Apple 2 rom

### ISSUE THREAD

**Issue by studio315b** [whscullin/apple2js#100]
Given the following input (text after the `|` is explanatory comments, not input):

```
F666G         | load the mini assembler
1000: LDA #FE | 
 STA 33       | set PROMPT to '>'
 JSR FD67     | Run the GetLineZ command in the system monitor
 STX 00       | Store the line length (X) at 00
 LDX #00      | X=0
 LDA 200,X    | Get the Xth char from the input buffer
 JSR FDED     | Run the COUT command from the system monitor
 INX          | X++
 CPX 00       | Compare X to line length
 BNE 100B     | if (X != length) goto the LDA 200,X line
 RTS          | Return
$1000G        | Run the code at 1000

HELLO ALL     | In response to > prompt
```

Expected output:
`HELLO ALL`

Actual output: byte listing as if `AL` was entered to monitor.

Additional runs (with various inputs) can produce all sorts of weird outputs. My guess is there's an error in the rom bytes, as this code works as expected on real hardware & other emulators. I'm guessing it has something to do with the space in the input, as I haven't gotten this on single word inputs

**Comment by iflan** [comment]
Very interesting. I noticed a couple of things:

*   The program is not exactly correct. On the first line `#FE` should be `#BE` if you want a `>` as a prompt.
*   The program does print out `HELLO ALL`, but then runs `ALL` as if it were typed in to the monitor (as you say).
*   As expected, `HELLO E003G` will return to BASIC.
*   `1000G` is exactly the same length as `HELLO`.

If you look at the [Apple //e monitor ROM listings](https://archive.org/details/Reference_Manual_Addendum_Monitor_ROM_Listings/page/n21/mode/1up), the monitor entry code is at `FF69`. One of the first things it does is `JSR GETLNZ`, which is the same as the program above. It then decodes the command (and all hex numbers before it) and then executes it at `FF82` with `JSR TOSUB`. `TOSUB` then executes the command through the jump table at `FFE3` by pushing and address on the stack and then doing an `RTS`. The `G` command is implemented at `FEB6`. The jump to the user address happens at `FEBC` as an indirect jump through `003A`. But note that this is a `JMP` not a `JSR`. This means that when the program's `RTS` happens, it's actually returning from the `JSR TOSUB`. As commented at `FF85`, this proceeds to process the next entry on the line—but that has been overwritten by the program. This is why anything after `HELLO` is interpreted by the monitor.

Thus, I don't think there's actually anything wrong with the ROM here.

Hope that helps!

**Comment by Bischoff** [comment]
I confirm the same happens with an Apple ][+ ROM from https://ftp.apple.asimov.net loaded into another emulator. That confirms there's nothing wrong with the ROM in Apple2js, and I think this issue could be closed.

**Comment by whscullin** [comment]
Glad to hear it.
