### ISSUE TITLE
Part of DHR screen visible when 40 column text activated

### ISSUE THREAD

**Issue by inexorabletash** [whscullin/apple2js#107]
Repro:
1. Start up in IIe mode (e.g. https://www.scullinsteel.com/apple2//e); turn on acceleration and monochrome mode
1. Grab an A2D build from https://github.com/a2stuff/a2d/releases
1. Mount the 2mg file, boot the system (PR#7 if necessary)
1. Wait for it to load (copy to RAMCard is slow, sorry about that...)
1. Once it's running: Apple > Screen Savers
1. Open Matrix

Result:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/771547/167336305-152906df-8988-4982-bf18-7b00844c74df.png">

Note one byte of the DHR screen visible on the left side of the screen.

There's no weird cycle counting going on; the order of softswitch flips to get from DHR to 40 column text mode might be slightly weird, and colored text mode is used if you have an RGB card, but that wouldn't result in this effect.

**Comment by iflan** [comment]
I tested this following the repro steps above and I can repro it only with the GL renderer _on_. With the GL renderer off, it looks fine:

![image](https://user-images.githubusercontent.com/7514156/167355608-7d6819b5-dd53-408a-85bf-d96ac29a6086.png)

Looking at the margins for text mode in the original report, it looks like text mode is actually not centered, but about 1/2 a character off. Measuring the image as best I can on the top scan line:

* Left edge to DHGR start: 82 - 24 = 58 px
* Left edge to text start: 94 - 24 = 70 px
* Right edge to text end: 1206 - 1138  = 68 px

Looking at `gl.ts`, I think the discrepancy comes from how `putImageData` is called. At [line 783](https://github.com/whscullin/apple2js/blob/c9a075fff9a19bc6cd2705d8ec60b10cb3bd91da/js/gl.ts#L783), the `x, y` is set for the first pixel of the screen based on the mode. `NTSC_DETAILS` comes from [line 471](https://github.com/whscullin/apple2shader/blob/c9a649db689c31e04d342021db5a39cd86337a24/screenEmu.js#L471) of `screenEmu.js`.

It looks like the easy fix is just to erase everything before calling `putImageData`.

**Comment by whscullin** [comment]
The one 80 column row difference between 80 column and 40 column mode is present in real hardware, so apple2shader is attempting to replicate that, but it's oblivious to transitions between the two. Clearing the image buffer when that transition happens should be sufficient.
