### ISSUE TITLE
Copy/paste no longer works with printer output

### ISSUE THREAD

**Issue by micahcowan** [whscullin/apple2js#142]
Hiya - I just updated my instance of apple2js, and I'm loving the added copy/paste feature - will surely save some time typing example programs or the like in ^_^

...But, I've just noticed that, whereas previously it had been possible to print to the virtual printer, select the text-field output and copy it, doing so now seems to copy just the current screen instead. Perhaps the copy handler should detect whether the virtual printer dialog is open?

It's not a huge deal, since the printer also offers a download option. But I figured you'd want to know.

**Comment by whscullin** [comment]
Ah, yes, I should be less aggressive about capturing copy/paste events. I think I have a fix that I can get in shortly.
