### ISSUE TITLE
Chrome: right click (mouse) context menu interferes with second button.

### ISSUE THREAD

**Issue by djmips** [whscullin/apple2js#21]
As seen in Pinball construction set when you are test playing your pinball the right mouse button activates the right flipper but the context menu pops up as well. 
One workaround that I do is to go into the browser console and execute. 
document.addEventListener('contextmenu', event => event.preventDefault());

**Comment by whscullin** [comment]
Thanks for pointing that out. That probably was a regression from when I ripped out jQuery.
