### ISSUE TITLE
65C02 emulation does not include all functional/cycle count differences

### ISSUE THREAD

**Issue by iflan** [whscullin/apple2js#39]
When browsing http://www.6502.org/tutorials/65c02opcodes.html, as one does, I noticed that the 65C02 emulation in apple2js does not cover all of the differences between the 6502 and 65C02 mentioned in these sections:
*   [Instructions with functional differences](http://www.6502.org/tutorials/65c02opcodes.html#6)
*   [Instructions with different cycle counts](http://www.6502.org/tutorials/65c02opcodes.html#7)
*   [Instructions with functional and cycle count differences](http://www.6502.org/tutorials/65c02opcodes.html#8)

It also doesn't cover the bogus instructions on the 6502, but I'm guessing that's OK.

**Comment by whscullin** [comment]
This was largely addressed by https://github.com/whscullin/apple2js/pull/88. I need to audit the 65C02 NOPs still, and I'm still on the fence about undocumented opcodes.

**Comment by whscullin** [comment]
The rest of this was addressed in https://github.com/whscullin/apple2js/pull/92, all opcodes, including undocumented, are implemented and cycle correct.
