### ISSUE TITLE
`format_utils.js` seems to have a bug recognizing `.po` files

### ISSUE THREAD

**Issue by iflan** [whscullin/apple2js#47]
In this line:

https://github.com/whscullin/apple2js/blob/e1b807ba9eaed0bd1f0cdf274edec2b19029d3c3/js/formats/format_utils.js#L289

it seems that `drive.fmt` should actually be `drive.format` as I can't find any code that sets `drive.fmt`. @whscullin can you confirm this? I have a Typescript conversion here:

https://github.com/iflan/apple2js/blob/f026ec001092f2358db031f6422d8786c6c76a54/js/formats/format_utils.ts#L297

that I believe fixes the issue. If you agree, I'll add it to PR #46.

Thanks!

**Comment by whscullin** [comment]
That seems right. I refactored this code at some point and must have messed that up.

**Comment by iflan** [comment]
Thanks for the confirmation. I've merged this with PR #46, which has grown considerably. Let me know if you want me to split that up in some way.
