### ISSUE TITLE
Gamepad support seems to have been removed in a refactor (so presumably not on purpose)

### ISSUE THREAD

**Issue by JasonWoof** [whscullin/apple2js#57]
Thank you for this amazing program! It's been a delight to play some of my childhood video games without having to install anything or fiddle with setup.

One of the games I wanted to play only works with the joystick though, and that didn't seem to work, so I took a look at the source code.

I found the function processGamepad really easily, but it wasn't being called anywhere.

Looks like it was removed in a refactor (commit bcbe36db0c) presumably by accident.

I added a call to processGamepad() right after this.tick() and that worked great for me when I did a build and opened up apple2js.html

Patch:
[re-enable-joystick.txt](https://github.com/whscullin/apple2js/files/5976919/re-enable-joystick.txt)

**Comment by whscullin** [comment]
Whoops! Thank you for catching that. I've applied your patch.

**Comment by JasonWoof** [comment]
Huzzah! Thanks :)
