### ISSUE TITLE
Disk #2 image name appears over Disk #1

### ISSUE THREAD

**Issue by celsowebber** [whscullin/apple2js#64]
Hi, thank you so much for this great piece of software! Congratulations.

While playing around at https://www.scullinsteel.com/apple2/, I've discovered that when I select a disk image no Drive #2, it loads correctly, but the "disk image file name" appears as if it was loaded no Drive #1. Previously loaded drive image on Drive #1 still works, but its "imagem name" gets overwritten in the interface with the Drive #2 selected "image name".

Again, congatulations for this great emulator!

**Comment by whscullin** [comment]
Turns out there were several places this was broken, but I think I've found them all.
