### ISSUE TITLE
On-screen keyboard does not create lowercase letters on the Apple //e

### ISSUE THREAD

**Issue by iflan** [whscullin/apple2js#72]
Something got broken somewhere because using the on-screen keyboard for lower-case letters is not working. Typing lowercase works fine.

**Comment by iflan** [comment]
Looks like this was broken by 37a3fb9bcd37ba0edae0d2654ca13b2596f89abc. I have a fix coming.

**Comment by whscullin** [comment]
"caps lock" defaults to on. What I see is that if "caps lock" is off, toggling shift on the on screen keyboard doesn't uppercase, but it does access symbols that require shift.

**Comment by whscullin** [comment]
OK, and now I can totally repro it. nm.

**Comment by iflan** [comment]
Fixed with #73.
