### ISSUE TITLE
Disk images used on website?

### ISSUE THREAD

**Issue by brainrecall** [whscullin/apple2js#90]
Hi, I'm working on creating a docker image of your work, but I now realized the emulator you have on your website at https://www.scullinsteel.com/apple//e has a lot of disk images that are not here in github. Can you make these available, if only as a zip if possible?

Thanks for your work!

**Comment by iflan** [comment]
Hi there,

I don't want to speak for Will, but consider creating your own disk images using the `bin/dsk2json` and `bin/index` utilities:

*   `dsk2json` takes a regular `.dsk` image that you can find on the 'net (like from the [Internet Archive](https://archive.org/download/Oregon_Trail_Disk_1_of_2)) and converts it into a `.json` file that the emulator can load.
* `index` looks in the `json/disks` directory and generates an `index.js` file containing all of the disks.

The whole workflow looks like this:
```shell
$ curl -L -O https://archive.org/download/Oregon_Trail_Disk_1_of_2/Oregon_Trail_Disk_1_of_2.dsk
$ ./bin/dsk2json --name="Oregon Trail Disk 1" --category="Games" Oregon_Trail_Disk_1_of_2.dsk > json/disks/Oregon_Trail_Disk_1_of_2.json
$ curl -L -O https://archive.org/download/Oregon_Trail_Disk_2_of_2/Oregon_Trail_Disk_2_of_2.dsk
$ ./bin/dsk2json --name="Oregon Trail Disk 2" --category="Games" Oregon_Trail_Disk_2_of_2.dsk > json/disks/Oregon_Trail_Disk_2_of_2.json
$ ./bin/index
```

You should be able to get your Dockerfile to do the downloading, converting, and indexing automatically.

Ian

**Comment by brainrecall** [comment]
Thanks Ian! I did see we could generate images, but Will had a good collection there. I whipped up some python to parse the index.js from the website and wget all the disk images. I'll commit that to my repo, but now I realize I did want the full version of Oregon Trail, which you gave as an example. Thanks!

**Comment by brainrecall** [comment]
And actually, I just realized he had the official Oregon Trail disks under the "Educational" group. The one in the "Game" group is some shareware version.

**Comment by iflan** [comment]
I'm glad that you were able to get what you needed. Please keep us posted on how your container comes along. I'd probably be interested in using it myself at some point. :-)

Feel free to close the issue if you think it's been handled.
